version: '3.8'

services:
  # WayMaker AI API (based on Dify)
  api:
    image: langgenius/dify-api:0.8.3
    environment:
      # Database
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=waymaker_user
      - DB_PASSWORD=${DB_PASSWORD:-waymaker2024}
      - DB_DATABASE=waymaker_ai
      
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-waymaker_redis}
      
      # App Config
      - SECRET_KEY=${SECRET_KEY:-waymaker-secret-key-2024}
      - APP_WEB_URL=https://waymaker.4children.3manwill.com
      - CONSOLE_WEB_URL=https://waymaker.4children.3manwill.com
      - APP_API_URL=https://waymaker.4children.3manwill.com
      - CONSOLE_API_URL=https://waymaker.4children.3manwill.com
      
      # AI Providers
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      
      # WayMaker AI Branding
      - APP_NAME=WayMaker AI
      - APP_DESCRIPTION="Your path to living God's will---step by step"
      
      # Storage
      - STORAGE_TYPE=local
      - STORAGE_LOCAL_PATH=/app/storage
      
      # Vector DB
      - WEAVIATE_ENDPOINT=http://weaviate:8080
      
      # Other
      - LOG_LEVEL=INFO
      - MIGRATION_ENABLED=true
    depends_on:
      - postgres
      - redis
      - weaviate
    volumes:
      - api_storage:/app/storage
      - waymaker_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # WayMaker AI Web Interface
  web:
    image: langgenius/dify-web:0.8.3
    environment:
      - NEXT_PUBLIC_API_PREFIX=https://waymaker.4children.3manwill.com/console/api
      - NEXT_PUBLIC_PUBLIC_API_PREFIX=https://waymaker.4children.3manwill.com/api
      - NEXT_PUBLIC_APP_URL=https://waymaker.4children.3manwill.com
      - NEXT_PUBLIC_DEPLOY_ENV=PRODUCTION
      - NEXT_PUBLIC_EDITION=SELF_HOSTED
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_TEXT_GENERATION_TIMEOUT_MS=60000
    depends_on:
      - api
    restart: unless-stopped

  # Background Worker
  worker:
    image: langgenius/dify-api:0.8.3
    command: celery -A app.celery worker -P gevent -c 1 --loglevel INFO -Q dataset,generation,mail,ops_trace,app_deletion
    environment:
      # Same as API
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=waymaker_user
      - DB_PASSWORD=${DB_PASSWORD:-waymaker2024}
      - DB_DATABASE=waymaker_ai
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-waymaker_redis}
      - SECRET_KEY=${SECRET_KEY:-waymaker-secret-key-2024}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - WEAVIATE_ENDPOINT=http://weaviate:8080
    depends_on:
      - postgres
      - redis
      - weaviate
    volumes:
      - api_storage:/app/storage
    restart: unless-stopped

  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=waymaker_ai
      - POSTGRES_USER=waymaker_user
      - POSTGRES_PASSWORD=${DB_PASSWORD:-waymaker2024}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U waymaker_user -d waymaker_ai"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-waymaker_redis}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Vector Database
  weaviate:
    image: semitechnologies/weaviate:1.19.0
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - CLUSTER_HOSTNAME=node1
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped

  # Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  weaviate_data:
  api_storage:
  waymaker_logs:

networks:
  default:
    name: waymaker_network