version: '3.8'
services:
  # API service
  api:
    image: langgenius/dify-api:0.6.16
    restart: always
    environment:
      # API configuration
      MODE: api
      LOG_LEVEL: INFO
      SECRET_KEY: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
      CONSOLE_WEB_URL: https://waymaker.4children.3manwill.com
      CONSOLE_API_URL: https://waymaker.4children.3manwill.com
      SERVICE_API_URL: https://waymaker.4children.3manwill.com
      APP_WEB_URL: https://waymaker.4children.3manwill.com
      # Database
      DB_USERNAME: postgres
      DB_PASSWORD: difyai123456
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: dify
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: difyai123456
      # Celery
      CELERY_BROKER_URL: redis://:difyai123456@redis:6379/1
      # Storage
      STORAGE_TYPE: local
      STORAGE_LOCAL_PATH: storage
      # AI Models
      GROQ_API_KEY: app-Mfi59Fz3YkFakdCfToUGoRaK
    depends_on:
      - db
      - redis
    volumes:
      - ./volumes/app/storage:/app/api/storage
    networks:
      - waymaker_network

  # Worker service
  worker:
    image: langgenius/dify-api:0.6.16
    restart: always
    environment:
      MODE: worker
      LOG_LEVEL: INFO
      SECRET_KEY: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
      DB_USERNAME: postgres
      DB_PASSWORD: difyai123456
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: dify
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: difyai123456
      CELERY_BROKER_URL: redis://:difyai123456@redis:6379/1
      GROQ_API_KEY: app-Mfi59Fz3YkFakdCfToUGoRaK
    depends_on:
      - db
      - redis
    volumes:
      - ./volumes/app/storage:/app/api/storage
    networks:
      - waymaker_network

  # Web service with HOSTNAME fix
  web:
    image: langgenius/dify-web:0.6.16
    restart: always
    environment:
      CONSOLE_API_URL: https://waymaker.4children.3manwill.com
      APP_API_URL: https://waymaker.4children.3manwill.com
      HOSTNAME: 0.0.0.0
    networks:
      - waymaker_network

  # Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: difyai123456
      POSTGRES_DB: dify
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    networks:
      - waymaker_network

  # Redis
  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - ./volumes/redis/data:/data
    command: redis-server --requirepass difyai123456
    networks:
      - waymaker_network

  # Nginx with proper API routing
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_SERVER_NAME: waymaker.4children.3manwill.com
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl
    depends_on:
      - api
      - web
    networks:
      - waymaker_network

networks:
  waymaker_network:
    driver: bridge

volumes:
  db_data:
  redis_data:
  app_storage: